version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g yarn typescript
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - yarn.lock
    - package.json
    - 'dist/**/*'
    - '.platform/**/*'
    - '.ebextensions/**/*'
  discard-paths: no
